id: '1620783977639'
alias: Hallway Sensor Lights On
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.hallway_motionsensor_occupancy
  to: 'on'
condition:
- condition: state
  entity_id: input_boolean.hallway_lights
  state: 'on'
action:
- choose:
  - conditions:
    - condition: time
      after: '23:30:00'
      before: 07:00:00
    sequence:
    - service: light.turn_on
      target:
        entity_id: light.hallway_ceiling_2
      data:
        transition: 2
  default:
  - service: light.turn_on
    target:
      entity_id: light.hallway_lights
    data:
      transition: 2
mode: single