id: '1620786258907'
alias: Livingroom Sensor Lights Off
description: ''
trigger:
- platform: state
  entity_id: group.livingarea_motionsensor
  to: 'off'
  for: 00:10:00
condition:
- condition: state
  entity_id: input_boolean.livingroom_lights
  state: 'on'
action:
- service: light.turn_off
  data:
    transition: 120
  target:
    entity_id: light.living_room_lights
mode: single