- platform: template
  covers:
    bedroom_blind:
      device_class: blind
      unique_id: "202105260100"
      friendly_name: "Bedroom Blind"
      position_template: "{{ is_state('cover.bedroom_rollerblind', 'closed') }}"
      open_cover:
        service: cover.open_cover
        entity_id: cover.bedroom_rollerblind
      close_cover:
        service: cover.close_cover
        entity_id: cover.bedroom_rollerblind
      stop_cover:
        service: cover.{{ 'open' if is_state('cover.bedroom_rollerblind', 'close') else 'close' }}_cover
        entity_id: cover.bedroom_rollerblind
      set_cover_position:
        service: cover.set_cover_position
        entity_id: cover.bedroom_rollerblind
        data:
          position: "{{position}}"
      icon_template: >-
          {% if is_state('cover.bedroom_blind', 'open') %}
            mdi:window-open
          {% else %}
            mdi:window-closed
          {% endif %}