- platform: group
  name: Outdoors Front
  entities:
    - light.carport_lights
    - light.footpath
- platform: group
  name: Master Bedroom
  entities:
    - light.master_bedroom_ceiling
    - light.master_bedroom_lamps
- platform: group
  name: Spare Bedroom
  entities:
    - light.spare_bedroom_ceiling
    - light.spare_bedroom_lamps
- platform: group
  name: Henrys Bedroom
  entities:
    - light.henrys_bedroom_ceiling
    - light.wled_henrys_light
- platform: group
  name: Office
  entities:
    - light.office_desk_lamp
    - light.wled_monitor
    - light.office_ceiling
    - light.office_wall_lamp
- platform: group
  name: Kitchen
  entities:
    - light.kitchen_ceiling
    - light.kitchen_cabinet
    - light.kitchen_sink
- platform: group
  name: Dining Room
  entities:
    - light.dining_room_cabinet
    - light.dining_room_chandelier
    - light.dining_room_picture
- platform: group
  name: Entrance
  entities:
    - light.entrance_chandelier
    - light.hallway_picture
- platform: group
  name: Hallway
  entities:
    - light.hallway_picture
    - light.hallway_ceiling
- platform: group
  name: Front Door
  entities:
    - light.front_door_ceiling
    - light.entrance_garden
- platform: group
  name: Ensuite
  entities:
    - light.ensuite_ceiling
    - light.ensuite_vanity
- platform: group
  name: Bathroom
  entities:
    - light.bathroom_ceiling
    - light.bathroom_vanity
- platform: switch
  name: Garden Lights
  entity_id: switch.garden_lights_shelly
# - platform: group
#   name: Master Bedroom Lamps
#   entities:
#     - light.master_bedroom_lamp_left
#     - light.master_bedroom_lamp_right
# - platform: group
#   name: Workshop
#   entities:
#     - light.workshop_downlight_1
#     - light.workshop_downlight_2
#     - light.workshop_downlight_3
# - platform: group
#   name: Spare Bedroom Lamps
#   entities:
#     - light.spare_bedroom_lamp_left
#     - light.spare_bedroom_lamp_right
# - platform: group
#   name: Henrys Bedroom Hue Play Bars
#   entities:
#     - light.henrys_room_hue_play_bar_1
#     - light.henrys_room_hue_play_bar_2
# - platform: group
#   name: Carport
#   entities:
#     - light.carport_light_front
#     - light.carport_light_middle
#     - light.carport_light_rear
