id: '1615700658792'
alias: Family Has Arrived
description: ''
trigger:
- platform: state
  to: home
  entity_id: group.device_tracker
  from: not_home
condition:
- condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'
action:
- service: script.turn_on
  target:
    entity_id:
    - script.arrive_home_day
    - script.arrive_home_night_after_2100
- service: input_boolean.turn_on
  target:
    entity_id: input_boolean.family_is_home
- service: notify.mobile_app_damiens_iphone
  data:
    title: Automation Complete
    message: Family Has Arrived
mode: single