alias: Mark person as just left
trigger:
- platform: state
  entity_id: person.damien
  from: home
  to: not_home
- platform: state
  entity_id: person.olia
  from: home
  to: not_home
action:
- service: input_select.select_option
  data_template:
    entity_id: "{% if trigger.entity_id == 'person.damien' %}\n  input_select.damien_status_dropdown\n\
      {% else %}\n  input_select.olia_status_dropdown\n{% endif %}\n"
    option: Just Left
id: 7bd148278475402aa206a3a0a305fb33