alias: Mark person as just arrived
trigger:
- platform: state
  entity_id: person.damien
  from: not_home
  to: home
- platform: state
  entity_id: person.olia
  from: not_home
  to: home
action:
- service: input_select.select_option
  data_template:
    entity_id: "{% if trigger.entity_id == 'person.damien' %}\n  input_select.damien_status_dropdown\n\
      {% else %}\n  input_select.olia_status_dropdown\n{% endif %}\n"
    option: "{% if trigger.entity_id == 'person.damien' %}\n  {% if states.input_select.damien_status_dropdown.state\
      \ == 'Just Left' %}\n    Home\n  {% else %}\n    Just Arrived\n  {% endif\
      \ %}\n{% else %}\n  {% if states.input_select.olia_status_dropdown.state ==\
      \ 'Just Left' %}\n    Home\n  {% else %}\n    Just Arrived\n  {% endif %}\n\
      {% endif %}\n"
id: 44f53985d9ec4115a8614e4301fc775e