alias: Mark person as away
trigger:
- platform: state
  entity_id: input_select.damien_status_dropdown
  to: Just Left
  for:
    minutes: 10
- platform: state
  entity_id: input_select.olia_status_dropdown
  to: Just Left
  for:
    minutes: 10
action:
- service: input_select.select_option
  data_template:
    entity_id: "{% if trigger.entity_id == 'input_select.damien_status_dropdown'\
      \ %}\n  input_select.damien_status_dropdown\n{% else %}\n  input_select.olia_status_dropdown\n\
      {% endif %}\n"
    option: Away
id: 1bd56a2d100c4f6986a9f5586d424f73