alias: Mark person as just left work
trigger:
- platform: state
  entity_id: person.damien
  from: Work Damien
  to: not_home
- platform: state
  entity_id: person.olia
  from: Work Olia
  to: not_home
action:
- service: input_select.select_option
  data_template:
    entity_id: "{% if trigger.entity_id == 'person.damien' %}\n  input_select.damien_status_dropdown\n\
      {% else %}\n  input_select.olia_status_dropdown\n{% endif %}\n"
    option: Just Left Work
id: 60ce9108ca6045688f5d7c9de3431f55