alias: Mark person as extended away
trigger:
- platform: state
  entity_id: input_select.damien_status_dropdown
  to: Away
  for:
    hours: 24
- platform: state
  entity_id: input_select.olia_status_dropdown
  to: Away
  for:
    hours: 24
action:
- service: input_select.select_option
  data_template:
    entity_id: "{% if trigger.entity_id == 'input_select.damien_status_dropdown'\
      \ %}\n  input_select.damien_status_dropdown\n{% else %}\n  input_select.olia_status_dropdown\n\
      {% endif %}\n"
    option: Extended Away
id: fef6a7ac40b3429cac15a78b5e6f00c9