id: '1615966781730'
alias: Olia Has Arrived
description: ''
trigger:
- platform: state
  entity_id: sensor.olia_status
  to: Just Arrived
condition:
- condition: state
  entity_id: person.damien
  state: home
- condition: time
  after: '10:00'
  before: '20:30'
action:
- service: notify.mobile_app_damiens_iphone
  data:
    message: Hurry, look busy!
    title: Olia Is Home
mode: single