id: '1622443511124'
alias: Guest Mode Off
description: ''
trigger:
- platform: state
  entity_id: input_boolean.guest_mode
  from: 'on'
  to: 'off'
condition:
- condition: state
  entity_id: group.family
  state: away
action:
- service: light.turn_off
  entity_id: all
mode: single