id: '1625398483414'
alias: Bathroom Fan
description: ''
trigger:
- platform: numeric_state
  entity_id: sensor.bathroom_weather_humidity
  above: '86'
condition: []
action:
- service: switch.turn_on
  target:
    entity_id: switch.shelly_bathroom_fan
- wait_for_trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_weather_humidity
    below: '85'
- service: switch.turn_off
  target:
    entity_id: switch.shelly_bathroom_fan
mode: single