id: '1625668269393'
alias: Ensuite Fan Shutoff
description: ''
trigger:
- platform: time_pattern
  minutes: /5
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: binary_sensor.shelly_ensuite_fan_switch
    state: 'on'
    for: 00:20:00
  - condition: numeric_state
    entity_id: sensor.ensuite_weather_humidity
    below: '85'
action:
- service: switch.turn_off
  target:
    entity_id: switch.shelly_ensuite_fan
mode: single