id: '20210814192242'
alias: Dryer Reset
description: ''
trigger:
- platform: state
  entity_id: miele.tumble_dryer
  to: In use
condition: []
action:
- service: input_boolean.turn_on
  target:
    entity_id: input_boolean.dryer
mode: single