id: '20210814192057'
alias: Dryer Has Finished
description: ''
trigger:
- platform: state
  entity_id: miele.tumble_dryer
  to: Finished
  from: In use
condition: []
action:
- service: input_boolean.turn_off
  target:
    entity_id: input_boolean.dryer