id: '1624072656512'
alias: Washing Machine Reset
description: ''
trigger:
- platform: state
  entity_id: miele.washing_machine
  to: In use
condition: []
action:
- service: input_boolean.turn_on
  target:
    entity_id: input_boolean.washing_machine
mode: single