id: '1624065282374'
alias: Washing Machine Finished Notification (Away)
description: ''
trigger:
- platform: state
  entity_id: input_boolean.washing_machine
  from: 'on'
  to: 'off'
condition:
- condition: state
  entity_id: group.family
  state: away
action:
- wait_for_trigger:
  - platform: state
    entity_id: group.family
    to: home
  - platform: state
    entity_id: binary_sensor.entrance_door_contact
    from: 'on'
    to: 'off'
- service: notify.alexa_media_kitchen_echo_show
  data:
    message: The washing machine has finished.
    data:
      type: announce
mode: single