id: '1621325374272'
alias: Bedroom Lamps Adaptive Lighting On
description: ''
trigger:
- platform: time
  at: 06:30:00
condition: []
action:
- service: switch.turn_on
  target:
    entity_id:
    - switch.adaptive_lighting_bedroom
    - switch.adaptive_lighting_bedroom_led_strips
mode: single