id: '1621170712747'
alias: Bedroom Lamps Adaptive Lighting Off
description: ''
trigger:
- platform: time
  at: '20:00:00'
condition: []
action:
- service: switch.turn_off
  target:
    entity_id:
    - switch.adaptive_lighting_bedroom
    - switch.adaptive_lighting_bedroom_led_strips
mode: single