id: '1624976182874'
alias: Adaptive Lighting Sleep Mode On - Living Areas
description: ''
trigger:
- platform: time
  at: '23:30:00'
condition: []
action:
- service: switch.turn_on
  target:
    entity_id:
    - switch.adaptive_lighting_sleep_mode_dining_table
    - switch.adaptive_lighting_sleep_mode_hallway_lights
    - switch.adaptive_lighting_sleep_mode_living_areas
mode: single