id: '1618908289405'
alias: Bedroom Lamps To Red
description: Bedroom Lamps Transition to Red at 8pm
trigger:
- platform: time
  at: '20:00:00'
condition:
- condition: state
  entity_id: light.bedroom_lamps
  state: 'on'
action:
- service: light.turn_on
  target:
    entity_id:
    - light.bedroom_lamps
    - light.bedroom_led_strips
  data:
    transition: 900
    rgb_color:
    - 255
    - 0
    - 0
    brightness_pct: 50
- service: light.turn_off
  target:
    entity_id: light.bedroom_pendant
  data:
    transition: 450
mode: single