alias: Bug Zapper Off
description: "Bug zapper will turn off at midnight"
mode: single
trigger:
  - platform: time
    at: "00:01"
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: switch.bug_zapper_smartplug
id: "202112191210"
