id: '20210629181510'
alias: Shelly - Balcony Light Toggle
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.shelly_balcony_light_switch
  to:
  - 'on'
  - 'off'
condition: []
action:
- service: light.toggle
  target:
    entity_id: light.balcony_lights
  data:
    transition: 1
mode: single