id: '20210718124000'
alias: Shelly - Bathroom Cabinet Light Toggle
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.shelly_bathroom_cabinet_light_switch
  to:
  - 'on'
  - 'off'
condition: []
action:
- service: switch.toggle
  target:
    entity_id: switch.shelly_bathroom_cabinet_light
mode: single