id: '1624782072875'
alias: Shelly - Dining Light Toggle
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.shelly_dining_light_switch
  to:
  - 'on'
  - 'off'
condition: []
action:
- service: switch.toggle
  target:
    entity_id: switch.dining_lights
mode: single