id: '20210702200300'
alias: Shelly - Ensuite Light Toggle
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.shelly_ensuite_light_switch
  to:
  - 'on'
  - 'off'
condition: []
action:
- service: light.toggle
  target:
    entity_id: light.ensuite_lights
  data:
    transition: 1
mode: single