id: '20210628201530'
alias: Shelly - Office Light Toggle
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.shelly_office_light_switch
  to:
  - 'on'
  - 'off'
condition: []
action:
- choose:
  - conditions:
    - condition: time
      after: 08:00
      before: '20:29'
    sequence:
    - service: light.toggle
      target:
        entity_id: light.office_lights
      data:
        transition: 1
  - conditions:
    - condition: time
      after: '20:30'
      before: 07:59
    sequence:
    - service: light.toggle
      data:
        transition: 1
      target:
        entity_id: light.office_lamps
  default: []
mode: single