id: shellies_announce
alias: 'Shellies Announce'
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce