alias: Tablet Inactivity Set Homepage
description: 'If no motion detected for 2 minutes and tablet is not on homepage, load homepage.'
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_tablet_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 2
condition:
  - condition: state
    entity_id: input_boolean.tablet_homepage
    state: 'off'
action:
  - service: python_script.fully
    data:
      cmd: loadStartUrl