alias: Tablet Homepage Helper On
description: 'Turns on tablet helper if browser navigates to home page'
mode: single
trigger:
  - platform: state
    entity_id: sensor.kitchen_tablet
    attribute: currentPage
    to: http://homeassistant:8123/lovelace/0?kiosk
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.tablet_homepage
