alias: Tablet Homepage Helper Off
description: 'Turns off tablet helper if browser navigates away from home page'
mode: single
trigger:
  - platform: state
    entity_id: sensor.kitchen_tablet
    attribute: currentPage
    from: http://homeassistant:8123/lovelace/0?kiosk
condition: []
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.tablet_homepage
